data=read.table("household_power_consumption.txt",sep=";",header=TRUE)
head(data)
str(data)
myDate=as.Date(data$Date)
head(myDate)
data1=subset(data,subset=(data$Date=="1/2/2007"|data$Date=="2/2/2007"))
length(data1)
str(data1)
head(data1)
tail(data1)
hist(as.numeric(data1$Global_active_power)/500,
     col="red",main="Global Active Power",xlab="Global Active Power(kilowatts)")
data1$Sequence=strptime(paste(as.character(data1$Date),as.character(data1$Time)),"%m/%d/%y %H:%M:%S")
head(data1)
data1$Sequence=paste(data1$Date,data1$Time)
plot(as.numeric(Global_active_power)~strptime(Sequence,"%m/%d/%y %H:%M:%S"),data=data1)
